# Generated by Django 5.1 on 2024-08-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoTWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joined_date',
            new_name='dob',
        ),
    ]
